spot1 = Spot.create(name: "City Caphe")
spot2 = Spot.create(name: "Mo Mo Street Food")
spot3 = Spot.create(name: "Itsu")
spot4 = Spot.create(name: "Wasabi")
spot5 = Spot.create(name: "Pret")
spot6 = Spot.create(name: "Eat")
spot7 = Spot.create(name: "LEON")
spot8 = Spot.create(name: "Whitecross Street Market")
